//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3074.
// 
namespace ChronoMobile.ChronoTrackWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RemoteServiceSoap", Namespace="http://ChronoTrack.org/")]
    public partial class RemoteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public RemoteService() {
            this.Url = "http://192.168.1.200/ChronoTrackWS/RemoteService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectTableLayout", RequestNamespace="http://ChronoTrack.org/", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project ProjectTableLayout() {
            object[] results = this.Invoke("ProjectTableLayout", new object[0]);
            return ((Project)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProjectTableLayout(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProjectTableLayout", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Project EndProjectTableLayout(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Project)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectCombinedTableLayout", RequestNamespace="http://ChronoTrack.org/", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project_combined ProjectCombinedTableLayout() {
            object[] results = this.Invoke("ProjectCombinedTableLayout", new object[0]);
            return ((Project_combined)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProjectCombinedTableLayout(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProjectCombinedTableLayout", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Project_combined EndProjectCombinedTableLayout(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Project_combined)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ValidationDetails", RequestElementName="ValidationDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ValidationDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidationDetailsResult")]
        public ValidateUserResponse ValidateUser(string userName, string password) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        userName,
                        password});
            return ((ValidateUserResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginValidateUser(string userName, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ValidateUser", new object[] {
                        userName,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public ValidateUserResponse EndValidateUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ValidateUserResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/DisconnectDetails", RequestElementName="DisconnectDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="DisconnectDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DisconnectDetailsResult")]
        public DisconnectResponse Disconnect() {
            object[] results = this.Invoke("Disconnect", new object[0]);
            return ((DisconnectResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDisconnect(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Disconnect", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public DisconnectResponse EndDisconnect(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DisconnectResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ScheduleDetails", RequestElementName="ScheduleDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ScheduleDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ScheduleDetailsResult")]
        public UserScheduleResponse UserSchedule() {
            object[] results = this.Invoke("UserSchedule", new object[0]);
            return ((UserScheduleResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUserSchedule(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UserSchedule", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public UserScheduleResponse EndUserSchedule(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserScheduleResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/RequestDetails", RequestElementName="RequestDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="RequestDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RequestDetailsResult")]
        public RequestResponse Requests(System.DateTime date, string resource) {
            object[] results = this.Invoke("Requests", new object[] {
                        date,
                        resource});
            return ((RequestResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRequests(System.DateTime date, string resource, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Requests", new object[] {
                        date,
                        resource}, callback, asyncState);
        }
        
        /// <remarks/>
        public RequestResponse EndRequests(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((RequestResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectDetails", RequestElementName="ProjectDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectDetailsResult")]
        public ProjectResponse Projects(string customer, System.DateTime date, string consultant, ProjectStatus status) {
            object[] results = this.Invoke("Projects", new object[] {
                        customer,
                        date,
                        consultant,
                        status});
            return ((ProjectResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProjects(string customer, System.DateTime date, string consultant, ProjectStatus status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Projects", new object[] {
                        customer,
                        date,
                        consultant,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProjectResponse EndProjects(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProjectResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectSummaryDetails", RequestElementName="ProjectSummaryDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectSummaryDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectSummaryDetailsResult")]
        public ProjectSummaryResponse ProjectSummary(string consultant, System.DateTime date) {
            object[] results = this.Invoke("ProjectSummary", new object[] {
                        consultant,
                        date});
            return ((ProjectSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProjectSummary(string consultant, System.DateTime date, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProjectSummary", new object[] {
                        consultant,
                        date}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProjectSummaryResponse EndProjectSummary(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProjectSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectNotesCreateResponse", RequestElementName="ProjectNotesCreateResponse", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectNotesCreateResponseResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectNotesCreateResponseResult")]
        public BaseResponse CreateProjectNote(int projectID, string description, string text) {
            object[] results = this.Invoke("CreateProjectNote", new object[] {
                        projectID,
                        description,
                        text});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateProjectNote(int projectID, string description, string text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateProjectNote", new object[] {
                        projectID,
                        description,
                        text}, callback, asyncState);
        }
        
        /// <remarks/>
        public BaseResponse EndCreateProjectNote(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectNoteDetails", RequestElementName="ProjectNoteDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectNoteDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectNoteDetailsResult")]
        public ProjectNotesResponse ProjectNotes(int projectID) {
            object[] results = this.Invoke("ProjectNotes", new object[] {
                        projectID});
            return ((ProjectNotesResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginProjectNotes(int projectID, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ProjectNotes", new object[] {
                        projectID}, callback, asyncState);
        }
        
        /// <remarks/>
        public ProjectNotesResponse EndProjectNotes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ProjectNotesResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class Project {
        
        private string synergygrfaField;
        
        private int project_idField;
        
        private string customer_idField;
        
        private string contract_idField;
        
        private int contract_project_idField;
        
        private string descriptionField;
        
        private System.DateTime start_dateField;
        
        private System.DateTime end_dateField;
        
        private int current_statusField;
        
        private string lead_consultantField;
        
        private string coordinatorField;
        
        private int approved_by_firstField;
        
        private int approved_by_lastField;
        
        private System.DateTime approved_dateField;
        
        private int approval_locationField;
        
        private int work_location_idField;
        
        private string textField;
        
        private string replication_keyField;
        
        /// <remarks/>
        public string Synergygrfa {
            get {
                return this.synergygrfaField;
            }
            set {
                this.synergygrfaField = value;
            }
        }
        
        /// <remarks/>
        public int Project_id {
            get {
                return this.project_idField;
            }
            set {
                this.project_idField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public string Contract_id {
            get {
                return this.contract_idField;
            }
            set {
                this.contract_idField = value;
            }
        }
        
        /// <remarks/>
        public int Contract_project_id {
            get {
                return this.contract_project_idField;
            }
            set {
                this.contract_project_idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Current_status {
            get {
                return this.current_statusField;
            }
            set {
                this.current_statusField = value;
            }
        }
        
        /// <remarks/>
        public string Lead_consultant {
            get {
                return this.lead_consultantField;
            }
            set {
                this.lead_consultantField = value;
            }
        }
        
        /// <remarks/>
        public string Coordinator {
            get {
                return this.coordinatorField;
            }
            set {
                this.coordinatorField = value;
            }
        }
        
        /// <remarks/>
        public int Approved_by_first {
            get {
                return this.approved_by_firstField;
            }
            set {
                this.approved_by_firstField = value;
            }
        }
        
        /// <remarks/>
        public int Approved_by_last {
            get {
                return this.approved_by_lastField;
            }
            set {
                this.approved_by_lastField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Approved_date {
            get {
                return this.approved_dateField;
            }
            set {
                this.approved_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Approval_location {
            get {
                return this.approval_locationField;
            }
            set {
                this.approval_locationField = value;
            }
        }
        
        /// <remarks/>
        public int Work_location_id {
            get {
                return this.work_location_idField;
            }
            set {
                this.work_location_idField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Replication_key {
            get {
                return this.replication_keyField;
            }
            set {
                this.replication_keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectNotesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectSummaryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserScheduleResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DisconnectResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateUserResponse))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class BaseResponse {
        
        private bool callStatusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool CallStatus {
            get {
                return this.callStatusField;
            }
            set {
                this.callStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ProjectNotesResponse : BaseResponse {
        
        private System.Data.DataTable projectNotesDataTableField;
        
        /// <remarks/>
        public System.Data.DataTable ProjectNotesDataTable {
            get {
                return this.projectNotesDataTableField;
            }
            set {
                this.projectNotesDataTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ProjectSummaryResponse : BaseResponse {
        
        private System.Data.DataTable projectDataTableCombinedField;
        
        /// <remarks/>
        public System.Data.DataTable ProjectDataTableCombined {
            get {
                return this.projectDataTableCombinedField;
            }
            set {
                this.projectDataTableCombinedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ProjectResponse : BaseResponse {
        
        private System.Data.DataTable projectDataTableField;
        
        /// <remarks/>
        public System.Data.DataTable ProjectDataTable {
            get {
                return this.projectDataTableField;
            }
            set {
                this.projectDataTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class RequestResponse : BaseResponse {
        
        private System.Data.DataTable requestDataTableField;
        
        /// <remarks/>
        public System.Data.DataTable RequestDataTable {
            get {
                return this.requestDataTableField;
            }
            set {
                this.requestDataTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class UserScheduleResponse : BaseResponse {
        
        private System.Data.DataTable userScheduleTableField;
        
        /// <remarks/>
        public System.Data.DataTable UserScheduleTable {
            get {
                return this.userScheduleTableField;
            }
            set {
                this.userScheduleTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class DisconnectResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ValidateUserResponse : BaseResponse {
        
        private string fullNameField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class Project_combined {
        
        private int project_idField;
        
        private string customer_nameField;
        
        private string customer_locationField;
        
        private string customer_contactField;
        
        private string contact_phoneField;
        
        private string descriptionField;
        
        private System.DateTime start_dateField;
        
        private System.DateTime end_dateField;
        
        private string current_statusField;
        
        private string consultant_full_nameField;
        
        private string coordinator_full_nameField;
        
        private string textField;
        
        /// <remarks/>
        public int Project_id {
            get {
                return this.project_idField;
            }
            set {
                this.project_idField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_name {
            get {
                return this.customer_nameField;
            }
            set {
                this.customer_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_location {
            get {
                return this.customer_locationField;
            }
            set {
                this.customer_locationField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_contact {
            get {
                return this.customer_contactField;
            }
            set {
                this.customer_contactField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_phone {
            get {
                return this.contact_phoneField;
            }
            set {
                this.contact_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
            }
        }
        
        /// <remarks/>
        public string Current_status {
            get {
                return this.current_statusField;
            }
            set {
                this.current_statusField = value;
            }
        }
        
        /// <remarks/>
        public string Consultant_full_name {
            get {
                return this.consultant_full_nameField;
            }
            set {
                this.consultant_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Coordinator_full_name {
            get {
                return this.coordinator_full_nameField;
            }
            set {
                this.coordinator_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public enum ProjectStatus {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Quoted,
        
        /// <remarks/>
        Signed,
        
        /// <remarks/>
        Implementation,
        
        /// <remarks/>
        PostProject,
        
        /// <remarks/>
        Completed,
    }
}
