//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace ChronoTrackMonitor.ChronoTrackWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RemoteServiceSoap", Namespace="http://ChronoTrack.org/")]
    public partial class RemoteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProjectTableLayoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProjectCombinedTableLayoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisconnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback UserScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback RequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProjectsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProjectSummaryOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateProjectNoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProjectNotesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RemoteService() {
            this.Url = global::ChronoTrackMonitor.Properties.Settings.Default.ChronoTrackMonitor_ChronoTrackWS_RemoteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProjectTableLayoutCompletedEventHandler ProjectTableLayoutCompleted;
        
        /// <remarks/>
        public event ProjectCombinedTableLayoutCompletedEventHandler ProjectCombinedTableLayoutCompleted;
        
        /// <remarks/>
        public event ValidateUserCompletedEventHandler ValidateUserCompleted;
        
        /// <remarks/>
        public event DisconnectCompletedEventHandler DisconnectCompleted;
        
        /// <remarks/>
        public event UserScheduleCompletedEventHandler UserScheduleCompleted;
        
        /// <remarks/>
        public event RequestsCompletedEventHandler RequestsCompleted;
        
        /// <remarks/>
        public event ProjectsCompletedEventHandler ProjectsCompleted;
        
        /// <remarks/>
        public event ProjectSummaryCompletedEventHandler ProjectSummaryCompleted;
        
        /// <remarks/>
        public event CreateProjectNoteCompletedEventHandler CreateProjectNoteCompleted;
        
        /// <remarks/>
        public event ProjectNotesCompletedEventHandler ProjectNotesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectTableLayout", RequestNamespace="http://ChronoTrack.org/", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project ProjectTableLayout() {
            object[] results = this.Invoke("ProjectTableLayout", new object[0]);
            return ((Project)(results[0]));
        }
        
        /// <remarks/>
        public void ProjectTableLayoutAsync() {
            this.ProjectTableLayoutAsync(null);
        }
        
        /// <remarks/>
        public void ProjectTableLayoutAsync(object userState) {
            if ((this.ProjectTableLayoutOperationCompleted == null)) {
                this.ProjectTableLayoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProjectTableLayoutOperationCompleted);
            }
            this.InvokeAsync("ProjectTableLayout", new object[0], this.ProjectTableLayoutOperationCompleted, userState);
        }
        
        private void OnProjectTableLayoutOperationCompleted(object arg) {
            if ((this.ProjectTableLayoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProjectTableLayoutCompleted(this, new ProjectTableLayoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectCombinedTableLayout", RequestNamespace="http://ChronoTrack.org/", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Project_combined ProjectCombinedTableLayout() {
            object[] results = this.Invoke("ProjectCombinedTableLayout", new object[0]);
            return ((Project_combined)(results[0]));
        }
        
        /// <remarks/>
        public void ProjectCombinedTableLayoutAsync() {
            this.ProjectCombinedTableLayoutAsync(null);
        }
        
        /// <remarks/>
        public void ProjectCombinedTableLayoutAsync(object userState) {
            if ((this.ProjectCombinedTableLayoutOperationCompleted == null)) {
                this.ProjectCombinedTableLayoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProjectCombinedTableLayoutOperationCompleted);
            }
            this.InvokeAsync("ProjectCombinedTableLayout", new object[0], this.ProjectCombinedTableLayoutOperationCompleted, userState);
        }
        
        private void OnProjectCombinedTableLayoutOperationCompleted(object arg) {
            if ((this.ProjectCombinedTableLayoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProjectCombinedTableLayoutCompleted(this, new ProjectCombinedTableLayoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ValidationDetails", RequestElementName="ValidationDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ValidationDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ValidationDetailsResult")]
        public ValidateUserResponse ValidateUser(string userName, string password) {
            object[] results = this.Invoke("ValidateUser", new object[] {
                        userName,
                        password});
            return ((ValidateUserResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string userName, string password) {
            this.ValidateUserAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void ValidateUserAsync(string userName, string password, object userState) {
            if ((this.ValidateUserOperationCompleted == null)) {
                this.ValidateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserOperationCompleted);
            }
            this.InvokeAsync("ValidateUser", new object[] {
                        userName,
                        password}, this.ValidateUserOperationCompleted, userState);
        }
        
        private void OnValidateUserOperationCompleted(object arg) {
            if ((this.ValidateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserCompleted(this, new ValidateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/DisconnectDetails", RequestElementName="DisconnectDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="DisconnectDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DisconnectDetailsResult")]
        public DisconnectResponse Disconnect() {
            object[] results = this.Invoke("Disconnect", new object[0]);
            return ((DisconnectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void DisconnectAsync() {
            this.DisconnectAsync(null);
        }
        
        /// <remarks/>
        public void DisconnectAsync(object userState) {
            if ((this.DisconnectOperationCompleted == null)) {
                this.DisconnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisconnectOperationCompleted);
            }
            this.InvokeAsync("Disconnect", new object[0], this.DisconnectOperationCompleted, userState);
        }
        
        private void OnDisconnectOperationCompleted(object arg) {
            if ((this.DisconnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisconnectCompleted(this, new DisconnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ScheduleDetails", RequestElementName="ScheduleDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ScheduleDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ScheduleDetailsResult")]
        public UserScheduleResponse UserSchedule() {
            object[] results = this.Invoke("UserSchedule", new object[0]);
            return ((UserScheduleResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UserScheduleAsync() {
            this.UserScheduleAsync(null);
        }
        
        /// <remarks/>
        public void UserScheduleAsync(object userState) {
            if ((this.UserScheduleOperationCompleted == null)) {
                this.UserScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUserScheduleOperationCompleted);
            }
            this.InvokeAsync("UserSchedule", new object[0], this.UserScheduleOperationCompleted, userState);
        }
        
        private void OnUserScheduleOperationCompleted(object arg) {
            if ((this.UserScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UserScheduleCompleted(this, new UserScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/RequestDetails", RequestElementName="RequestDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="RequestDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("RequestDetailsResult")]
        public RequestResponse Requests(System.DateTime date, string resource) {
            object[] results = this.Invoke("Requests", new object[] {
                        date,
                        resource});
            return ((RequestResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RequestsAsync(System.DateTime date, string resource) {
            this.RequestsAsync(date, resource, null);
        }
        
        /// <remarks/>
        public void RequestsAsync(System.DateTime date, string resource, object userState) {
            if ((this.RequestsOperationCompleted == null)) {
                this.RequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestsOperationCompleted);
            }
            this.InvokeAsync("Requests", new object[] {
                        date,
                        resource}, this.RequestsOperationCompleted, userState);
        }
        
        private void OnRequestsOperationCompleted(object arg) {
            if ((this.RequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestsCompleted(this, new RequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectDetails", RequestElementName="ProjectDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectDetailsResult")]
        public ProjectResponse Projects(string customer, System.DateTime date, string consultant, ProjectStatus status) {
            object[] results = this.Invoke("Projects", new object[] {
                        customer,
                        date,
                        consultant,
                        status});
            return ((ProjectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProjectsAsync(string customer, System.DateTime date, string consultant, ProjectStatus status) {
            this.ProjectsAsync(customer, date, consultant, status, null);
        }
        
        /// <remarks/>
        public void ProjectsAsync(string customer, System.DateTime date, string consultant, ProjectStatus status, object userState) {
            if ((this.ProjectsOperationCompleted == null)) {
                this.ProjectsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProjectsOperationCompleted);
            }
            this.InvokeAsync("Projects", new object[] {
                        customer,
                        date,
                        consultant,
                        status}, this.ProjectsOperationCompleted, userState);
        }
        
        private void OnProjectsOperationCompleted(object arg) {
            if ((this.ProjectsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProjectsCompleted(this, new ProjectsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectSummaryDetails", RequestElementName="ProjectSummaryDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectSummaryDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectSummaryDetailsResult")]
        public ProjectSummaryResponse ProjectSummary(string consultant, System.DateTime date) {
            object[] results = this.Invoke("ProjectSummary", new object[] {
                        consultant,
                        date});
            return ((ProjectSummaryResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProjectSummaryAsync(string consultant, System.DateTime date) {
            this.ProjectSummaryAsync(consultant, date, null);
        }
        
        /// <remarks/>
        public void ProjectSummaryAsync(string consultant, System.DateTime date, object userState) {
            if ((this.ProjectSummaryOperationCompleted == null)) {
                this.ProjectSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProjectSummaryOperationCompleted);
            }
            this.InvokeAsync("ProjectSummary", new object[] {
                        consultant,
                        date}, this.ProjectSummaryOperationCompleted, userState);
        }
        
        private void OnProjectSummaryOperationCompleted(object arg) {
            if ((this.ProjectSummaryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProjectSummaryCompleted(this, new ProjectSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectNotesCreateResponse", RequestElementName="ProjectNotesCreateResponse", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectNotesCreateResponseResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectNotesCreateResponseResult")]
        public BaseResponse CreateProjectNote(int projectID, string description, string text) {
            object[] results = this.Invoke("CreateProjectNote", new object[] {
                        projectID,
                        description,
                        text});
            return ((BaseResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProjectNoteAsync(int projectID, string description, string text) {
            this.CreateProjectNoteAsync(projectID, description, text, null);
        }
        
        /// <remarks/>
        public void CreateProjectNoteAsync(int projectID, string description, string text, object userState) {
            if ((this.CreateProjectNoteOperationCompleted == null)) {
                this.CreateProjectNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProjectNoteOperationCompleted);
            }
            this.InvokeAsync("CreateProjectNote", new object[] {
                        projectID,
                        description,
                        text}, this.CreateProjectNoteOperationCompleted, userState);
        }
        
        private void OnCreateProjectNoteOperationCompleted(object arg) {
            if ((this.CreateProjectNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProjectNoteCompleted(this, new CreateProjectNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ChronoTrack.org/ProjectNoteDetails", RequestElementName="ProjectNoteDetails", RequestNamespace="http://ChronoTrack.org/", ResponseElementName="ProjectNoteDetailsResponse", ResponseNamespace="http://ChronoTrack.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ProjectNoteDetailsResult")]
        public ProjectNotesResponse ProjectNotes(int projectID) {
            object[] results = this.Invoke("ProjectNotes", new object[] {
                        projectID});
            return ((ProjectNotesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ProjectNotesAsync(int projectID) {
            this.ProjectNotesAsync(projectID, null);
        }
        
        /// <remarks/>
        public void ProjectNotesAsync(int projectID, object userState) {
            if ((this.ProjectNotesOperationCompleted == null)) {
                this.ProjectNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProjectNotesOperationCompleted);
            }
            this.InvokeAsync("ProjectNotes", new object[] {
                        projectID}, this.ProjectNotesOperationCompleted, userState);
        }
        
        private void OnProjectNotesOperationCompleted(object arg) {
            if ((this.ProjectNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProjectNotesCompleted(this, new ProjectNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class Project {
        
        private string synergygrfaField;
        
        private int project_idField;
        
        private string customer_idField;
        
        private string contract_idField;
        
        private int contract_project_idField;
        
        private string descriptionField;
        
        private System.DateTime start_dateField;
        
        private System.DateTime end_dateField;
        
        private int current_statusField;
        
        private string lead_consultantField;
        
        private string coordinatorField;
        
        private int approved_by_firstField;
        
        private int approved_by_lastField;
        
        private System.DateTime approved_dateField;
        
        private int approval_locationField;
        
        private int work_location_idField;
        
        private string textField;
        
        private string replication_keyField;
        
        /// <remarks/>
        public string Synergygrfa {
            get {
                return this.synergygrfaField;
            }
            set {
                this.synergygrfaField = value;
            }
        }
        
        /// <remarks/>
        public int Project_id {
            get {
                return this.project_idField;
            }
            set {
                this.project_idField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_id {
            get {
                return this.customer_idField;
            }
            set {
                this.customer_idField = value;
            }
        }
        
        /// <remarks/>
        public string Contract_id {
            get {
                return this.contract_idField;
            }
            set {
                this.contract_idField = value;
            }
        }
        
        /// <remarks/>
        public int Contract_project_id {
            get {
                return this.contract_project_idField;
            }
            set {
                this.contract_project_idField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Current_status {
            get {
                return this.current_statusField;
            }
            set {
                this.current_statusField = value;
            }
        }
        
        /// <remarks/>
        public string Lead_consultant {
            get {
                return this.lead_consultantField;
            }
            set {
                this.lead_consultantField = value;
            }
        }
        
        /// <remarks/>
        public string Coordinator {
            get {
                return this.coordinatorField;
            }
            set {
                this.coordinatorField = value;
            }
        }
        
        /// <remarks/>
        public int Approved_by_first {
            get {
                return this.approved_by_firstField;
            }
            set {
                this.approved_by_firstField = value;
            }
        }
        
        /// <remarks/>
        public int Approved_by_last {
            get {
                return this.approved_by_lastField;
            }
            set {
                this.approved_by_lastField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Approved_date {
            get {
                return this.approved_dateField;
            }
            set {
                this.approved_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Approval_location {
            get {
                return this.approval_locationField;
            }
            set {
                this.approval_locationField = value;
            }
        }
        
        /// <remarks/>
        public int Work_location_id {
            get {
                return this.work_location_idField;
            }
            set {
                this.work_location_idField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Replication_key {
            get {
                return this.replication_keyField;
            }
            set {
                this.replication_keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectNotesResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectSummaryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProjectResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserScheduleResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DisconnectResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ValidateUserResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class BaseResponse {
        
        private bool callStatusField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public bool CallStatus {
            get {
                return this.callStatusField;
            }
            set {
                this.callStatusField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ProjectNotesResponse : BaseResponse {
        
        private System.Data.DataTable projectNotesDataTableField;
        
        /// <remarks/>
        public System.Data.DataTable ProjectNotesDataTable {
            get {
                return this.projectNotesDataTableField;
            }
            set {
                this.projectNotesDataTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ProjectSummaryResponse : BaseResponse {
        
        private System.Data.DataTable projectDataTableCombinedField;
        
        /// <remarks/>
        public System.Data.DataTable ProjectDataTableCombined {
            get {
                return this.projectDataTableCombinedField;
            }
            set {
                this.projectDataTableCombinedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ProjectResponse : BaseResponse {
        
        private System.Data.DataTable projectDataTableField;
        
        /// <remarks/>
        public System.Data.DataTable ProjectDataTable {
            get {
                return this.projectDataTableField;
            }
            set {
                this.projectDataTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class RequestResponse : BaseResponse {
        
        private System.Data.DataTable requestDataTableField;
        
        /// <remarks/>
        public System.Data.DataTable RequestDataTable {
            get {
                return this.requestDataTableField;
            }
            set {
                this.requestDataTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class UserScheduleResponse : BaseResponse {
        
        private System.Data.DataTable userScheduleTableField;
        
        /// <remarks/>
        public System.Data.DataTable UserScheduleTable {
            get {
                return this.userScheduleTableField;
            }
            set {
                this.userScheduleTableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class DisconnectResponse : BaseResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class ValidateUserResponse : BaseResponse {
        
        private string fullNameField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public partial class Project_combined {
        
        private int project_idField;
        
        private string customer_nameField;
        
        private string customer_locationField;
        
        private string customer_contactField;
        
        private string contact_phoneField;
        
        private string descriptionField;
        
        private System.DateTime start_dateField;
        
        private System.DateTime end_dateField;
        
        private string current_statusField;
        
        private string consultant_full_nameField;
        
        private string coordinator_full_nameField;
        
        private string textField;
        
        /// <remarks/>
        public int Project_id {
            get {
                return this.project_idField;
            }
            set {
                this.project_idField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_name {
            get {
                return this.customer_nameField;
            }
            set {
                this.customer_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_location {
            get {
                return this.customer_locationField;
            }
            set {
                this.customer_locationField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_contact {
            get {
                return this.customer_contactField;
            }
            set {
                this.customer_contactField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_phone {
            get {
                return this.contact_phoneField;
            }
            set {
                this.contact_phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start_date {
            get {
                return this.start_dateField;
            }
            set {
                this.start_dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End_date {
            get {
                return this.end_dateField;
            }
            set {
                this.end_dateField = value;
            }
        }
        
        /// <remarks/>
        public string Current_status {
            get {
                return this.current_statusField;
            }
            set {
                this.current_statusField = value;
            }
        }
        
        /// <remarks/>
        public string Consultant_full_name {
            get {
                return this.consultant_full_nameField;
            }
            set {
                this.consultant_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Coordinator_full_name {
            get {
                return this.coordinator_full_nameField;
            }
            set {
                this.coordinator_full_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ChronoTrack.org/")]
    public enum ProjectStatus {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Quoted,
        
        /// <remarks/>
        Signed,
        
        /// <remarks/>
        Implementation,
        
        /// <remarks/>
        PostProject,
        
        /// <remarks/>
        Completed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProjectTableLayoutCompletedEventHandler(object sender, ProjectTableLayoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectTableLayoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProjectTableLayoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Project Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Project)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProjectCombinedTableLayoutCompletedEventHandler(object sender, ProjectCombinedTableLayoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectCombinedTableLayoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProjectCombinedTableLayoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Project_combined Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Project_combined)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ValidateUserCompletedEventHandler(object sender, ValidateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidateUserResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidateUserResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void DisconnectCompletedEventHandler(object sender, DisconnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisconnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisconnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DisconnectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DisconnectResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void UserScheduleCompletedEventHandler(object sender, UserScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UserScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UserScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserScheduleResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserScheduleResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void RequestsCompletedEventHandler(object sender, RequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RequestResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProjectsCompletedEventHandler(object sender, ProjectsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProjectsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProjectSummaryCompletedEventHandler(object sender, ProjectSummaryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProjectSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectSummaryResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectSummaryResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void CreateProjectNoteCompletedEventHandler(object sender, CreateProjectNoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProjectNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProjectNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BaseResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BaseResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void ProjectNotesCompletedEventHandler(object sender, ProjectNotesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProjectNotesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProjectNotesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProjectNotesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProjectNotesResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591