//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChronoTrackMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChronoTrackMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon FolderNew {
            get {
                object obj = ResourceManager.GetObject("FolderNew", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChronoTrack - New project notification.
        /// </summary>
        internal static string mBalloonCaption {
            get {
                return ResourceManager.GetString("mBalloonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure monitor.
        /// </summary>
        internal static string mConfigureMonitor {
            get {
                return ResourceManager.GetString("mConfigureMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit ChronoTrack monitor.
        /// </summary>
        internal static string mExitMonitor {
            get {
                return ResourceManager.GetString("mExitMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChronoTrack Notification Monitor.
        /// </summary>
        internal static string mMonitorTitle {
            get {
                return ResourceManager.GetString("mMonitorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChronoTrack Notification Monitor {0} new projects.
        /// </summary>
        internal static string mMonitorTitleNewProjects {
            get {
                return ResourceManager.GetString("mMonitorTitleNewProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project viewer.
        /// </summary>
        internal static string mOpenProjectView {
            get {
                return ResourceManager.GetString("mOpenProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a total of {0} new projects assigned to you.
        /// </summary>
        internal static string mProjectCount {
            get {
                return ResourceManager.GetString("mProjectCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}, these are you current projects..
        /// </summary>
        internal static string mProjectViewCaption {
            get {
                return ResourceManager.GetString("mProjectViewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a total of {0} new request assigned to you.
        /// </summary>
        internal static string mRequestCount {
            get {
                return ResourceManager.GetString("mRequestCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the system and connection settings.
        /// </summary>
        internal static string mResetSystemSettings {
            get {
                return ResourceManager.GetString("mResetSystemSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Note_Add {
            get {
                object obj = ResourceManager.GetObject("Note_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
